caterwaul.module( 'bench' ,function(c) { (function( ) {var init=function() {;
return( ( ($( 'body' ) ) .append(benchmark_interface() ) ) , ($( '#builtins' ) .remove() ) ) } ,benchmark_interface=function() {;
return jQuery( "<div>" ) .append(jQuery( "<div>" ) .addClass( "right" ) .append(builtins() ,log() ) ) .append(function_input_area() ) } ,log=function() {;
return jQuery( "<table>" ) .addClass( "log" ) .append(jQuery( "<tr>" ) .append(jQuery( "<th>" ) .append(jQuery( "<span>" + ( 'Average (ms)' ) + "</span>" ) ) .add(jQuery( "<th>" ) .append(jQuery( "<span>" + ( 'Min' ) + "</span>" ) ) ) .add(jQuery( "<th>" ) .append(jQuery( "<span>" + ( 'Max' ) + "</span>" ) ) ) .add(jQuery( "<th>" ) .append(jQuery( "<span>" + ( 'SD' ) + "</span>" ) ) ) .add(jQuery( "<th>" ) .append(jQuery( "<span>" + ( 'N' ) + "</span>" ) ) ) ) ) } ,function_input_area=function() {;
return(function( ) {var run=function(e) {;
return run_benchmark($( 'textarea.setup' ) .val() ,$( 'textarea.bench' ) .val() ) } ,checks_syntax=function(t) {;
return( (t) .keyup(check(t) ) ) .change(check(t) ) } ,check=function(t) {;
return function(e) {;
return(function( ) {try{return( ( (compile(t.val() ) ) , (t.removeClass( 'invalid' ) ) ) ) }catch(e) {return(t.addClass( 'invalid' ) ) } } ) .call(this) } } ;
return(jQuery( "<div>" ) .addClass( "function-input" ) .append(jQuery( "<pre>" ) .append(jQuery( "<span>" + ( '(function () {' ) + "</span>" ) ) .add(jQuery( "<div>" ) .addClass( "indent" ) .append(checks_syntax(jQuery( "<textarea>" ) .addClass( "setup" ) ) .add(jQuery( "<pre>" ) .append(jQuery( "<span>" + ( 'benchmark(function () {' ) + "</span>" ) ) ) .add(jQuery( "<div>" ) .addClass( "indent" ) .append(checks_syntax(jQuery( "<textarea>" ) .addClass( "bench" ) ) ) ) .add(jQuery( "<pre>" ) .append(jQuery( "<span>" + ( '});' ) + "</span>" ) ) ) ) ) .add(jQuery( "<pre>" ) .append(jQuery( "<span>" + ( '})()' ) + "</span>" ) ) ) .add(jQuery( "<pre>" ) .addClass( "errors" ) ) .add(jQuery( "<div>" ) .addClass( "controls" ) .append(jQuery( "<button>" ) .addClass( "run" ) .append(jQuery( "<span>" + ( 'Run' ) + "</span>" ) ) .click(run) ) ) ) ) } ) .call(this) } ,builtins=function() {;
return jQuery( "<div>" ) .addClass( "builtins" ) .append(jQuery( "<span>" + ( 'Examples: ' ) + "</span>" ) .add(jQuery( "<ul>" ) .append( (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( ( (function(x,x0,xi,xl,xs,xr) {return(function( ) {var name=$(x) .find( 'a' ) .text() ,populate=populator($(x) .find( '.setup' ) .text() ,$(x) .find( '.bench' ) .text() ) ;
return( (function(it) {return(it[0] ) } ) .call(this, (jQuery( "<li>" ) .append(clickable(jQuery( "<a>" ) .text(name) ) .click(populate) ) ) ) ) } ) .call(this) } ) .call(this,x,x0,xi,xl,xs,xr) ) ) ;
return xr} ) .call(this,$( '#builtins > div' ) ) ) ) ) } ,clickable=function(a) {;
return a.attr( 'href' , 'javascript:void 0' ) } ,dangerous=function(message,f) {;
return( ($( 'pre.errors' ) .empty() ) , ( (function( ) {try{return(f() ) }catch(e) {return($( 'pre.errors' ) .text( ( 'Error ' + (message) + ': ' + (e) + '' ) ) ,undefined) } } ) .call(this) ) ) } ,compile=function(source) {;
return caterwaul() ( ( '(function () {' + (source) + '})' ) ) } ,populator=function(setup,bench) {;
return function() {;
return( ( ($( 'textarea.setup' ) ) .val(setup) ) , ( ($( 'textarea.bench' ) ) .val(bench) ) ) } } ,run_benchmark=function(s,b) {;
return(function( ) {var execute_benchmark=function() {;
return compiled&&run() && ($( 'table.log' ) ) .append(the_log_entry() ) } ,populate=populator(s,b) ,nuke=function() {;
return $(this) .parents( 'tr' ) .first() .remove() } ,log_entry=function(avg,min,max,sd,n) {;
return jQuery( "<tr>" ) .append(jQuery( "<td>" ) .text(avg) .add(jQuery( "<td>" ) .text(min) ) .add(jQuery( "<td>" ) .text(max) ) .add(jQuery( "<td>" ) .text(sd) ) .add(jQuery( "<td>" ) .text(n) ) .add(jQuery( "<td>" ) .append(clickable(jQuery( "<a>" ) .append(jQuery( "<span>" + ( 'source' ) + "</span>" ) ) ) .click(populate) ) ) .add(jQuery( "<td>" ) .append(clickable(jQuery( "<a>" ) .append(jQuery( "<span>" + ( '[x]' ) + "</span>" ) ) ) .click(nuke) ) ) ) } ,recorded_times= [ ] ,record=function(time) {;
return(recorded_times) .push(time) } ,benchmark=function(f) {;
return(function( ) {var start= +new Date,last=start;
return( (function(xs) {var x,x0,xi,xl,xr;
for(var x=xs,xi=0,x0,xl;
x0= ( +new Date-start<5000) ;
 ++xi)x= (f() ,record( - (last- (last= +new Date) ) ) ) ;
return x} ) .call(this,null) ) } ) .call(this) } ,environment=function() {;
return{benchmark:benchmark,million:1000000,thousand:1000,billion:1000000000} } ,run=function() {;
return dangerous( 'running benchmark function' ,compiled) } ,compiled=dangerous( 'compiling benchmark function' ,function(_) {return caterwaul() ( ( '(function () {' + (s) + '; benchmark(function () {' + (b) + '}); return true})' ) ,environment() ) } ) ,the_log_entry=function() {;
return(function( ) {var average= (function(xs) {var x,x0,xi,xl,xr;
for(var x0=xs[0] ,xi=1,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,x0= (x+x0) ;
return x0} ) .call(this,recorded_times) /recorded_times.length;
return(log_entry(average.toFixed(3) , (function(xs) {var x,x0,xi,xl,xr;
for(var x0=xs[0] ,xi=1,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,x0= (Math.min(x,x0) ) ;
return x0} ) .call(this,recorded_times) , (function(xs) {var x,x0,xi,xl,xr;
for(var x0=xs[0] ,xi=1,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,x0= (Math.max(x,x0) ) ;
return x0} ) .call(this,recorded_times) , (function(it) {return(it.toFixed(3) ) } ) .call(this, (Math.sqrt( (function(xs) {var x,x0,xi,xl,xr;
for(var x0= (0) ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,x0= (x0+ (x-average) * (x-average) ) ;
return x0} ) .call(this,recorded_times) ) ) ) ,recorded_times.length) ) } ) .call(this) } ;
return(execute_benchmark() ) } ) .call(this) } ;
return($(init) ) } ) .call(this) } ) ;
